# Use the official .NET 6 SDK image
FROM mcr.microsoft.com/dotnet/sdk:6.0 AS build
WORKDIR /app

# Copy everything and publish the release
COPY . .
RUN dotnet publish -c Release -o out

# Use the official ASP.NET Core Runtime as the base image
FROM mcr.microsoft.com/dotnet/aspnet:6.0 AS runtime
WORKDIR /app
COPY --from=build /app/out .

ENTRYPOINT ["dotnet", "ChuckItApi.dll"]
