version: '3.4'

services:
  api:
    image: chuckit_api
    build:
      context: .
      dockerfile: Dockerfile
    environment:
      - ASPNETCORE_ENVIRONMENT=Development
      - AWS__Profile=default
      - AWS__Region=ca-central-1
      - AWS__BucketName=YourS3BucketName
      - Jwt__Key=${JWT_KEY}
      - Jwt__Issuer=http://localhost
      - Jwt__Audience=http://localhost
      - DB_HOST=db
      - DB_DATABASE=${DB_DATABASE}
      - DB_USERNAME=${DB_USERNAME}
      - DB_PASSWORD=${DB_PASSWORD}
      - DB_PORT=${DB_PORT}
    ports:
      - "5000:80"
    depends_on:
      - db

  db:
    image: postgres:13
    environment:
      POSTGRES_USER: ${DB_USERNAME}
      POSTGRES_PASSWORD: ${DB_PASSWORD}
      POSTGRES_DB: ${DB_DATABASE}
    ports:
      - "5432:5432"
